### ISSUE TITLE
[Android Bootcamp] Project 2: Grid Image View - Ready for Review

### ISSUE THREAD

**Issue by sje397** [sje397/GridImageSearch#1]
My app is complete, please review. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
Good job finishing all required stories and some of the optionals. A few notes after checking out the code:
- Nice work setting up shared preferences to persist the settings between activities
- Consider using spinners (with populated values) to allow users to select filters
- Consider adding the share intent to the image detail view!
- Consider using Parcelable instead of Serializable (benefits)
- Consider using  StaggeredGridView
- Good to see search field in the SearchView
- Consider adding progress bars to your app whenever a network request goes out.

Also, here's a more detailed Project 2 Feedback Guide here which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission.

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
